from enum import Enum

class ErrorStatuses(Enum):
    WALLET_NOT_FOUND = "WALLET NOT FOUND"
    USER_NOT_FOUND = "USER NOT FOUND"
    STOCK_NOT_FOUND = "STOCK NOT FOUND"
    PRICE_NOT_FOUND = "PRICE NOT FOUND"
    USER_ALREADY_EXISTS = "USER ALREADY EXISTS"
    HISTORY_NOT_FOUND = "STOCK PRICE HISTORY NOT FOUND"