"""exchange rate next_update

Revision ID: 34802fe132da
Revises: b0af99027df3
Create Date: 2026-07-07 16:55:15.631518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34802fe132da'
down_revision = 'b0af99027df3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchange_rates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_update', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchange_rates', schema=None) as batch_op:
        batch_op.drop_column('next_update')

    # ### end Alembic commands ###
