"""shadow links and notifications

Revision ID: b0af99027df3
Revises: 74b08526d730
Create Date: 2026-07-06 10:26:27.698868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0af99027df3'
down_revision = '74b08526d730'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('SHADOW_INVITE', 'SHADOW_TRADE', 'SHADOW_ACCEPTED', name='notificationtype'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notification_user_read_created', ['user_id', 'is_read', 'created_at'], unique=False)

    op.create_table('shadow_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('shadow_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'REVOKED', name='shadowstatus'), nullable=False),
    sa.Column('initiated_by', sa.Enum('SUBJECT', 'SHADOW', name='initiatedby'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shadow_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'shadow_id', name='uq_shadow_link_pair')
    )
    with op.batch_alter_table('shadow_links', schema=None) as batch_op:
        batch_op.create_index('ix_shadow_link_shadow_status', ['shadow_id', 'status'], unique=False)
        batch_op.create_index('ix_shadow_link_subject_status', ['subject_id', 'status'], unique=False)

    # Add with a server_default so existing rows backfill to false, then drop the
    # default so the column matches the model (Python-side default only).
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_shadow_discoverable', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.alter_column('is_shadow_discoverable', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_shadow_discoverable')

    with op.batch_alter_table('shadow_links', schema=None) as batch_op:
        batch_op.drop_index('ix_shadow_link_subject_status')
        batch_op.drop_index('ix_shadow_link_shadow_status')

    op.drop_table('shadow_links')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notification_user_read_created')

    op.drop_table('notifications')

    # Postgres keeps enum types after their tables are dropped; remove them so a
    # subsequent re-upgrade can recreate them cleanly.
    bind = op.get_bind()
    sa.Enum(name='shadowstatus').drop(bind, checkfirst=True)
    sa.Enum(name='initiatedby').drop(bind, checkfirst=True)
    sa.Enum(name='notificationtype').drop(bind, checkfirst=True)
    # ### end Alembic commands ###
